import '../globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Topbar from '../_components/Topbar'
import Footer from '../_components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Giestas Granitos',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
		return (
				<html lang="en">
						<body className={inter.className + " bg-white"}>
							<div className="flex flex-col min-h-screen mx-auto bg-white">
							<Topbar />
								<div className="flex-grow">
									<main className="text-black">
										{children}
									</main>
								</div>
								<Footer />
							</div>
						</body>
				</html>
		)
}